export const KEYSTORE = {
  SET_LOCALE: 'SET_LOCALE',
  SET_CURRENCY: 'SET_CURRENCY',
  SET_FIAT_RATE: 'SET_FIAT_RATE',
  TOKEN_JWT: 'TOKEN_JWT',
  SET_SETTINGS: 'SET_SETTINGS',
  SET_WALLET_CONNECT: 'SET_WALLET_CONNECT',
  SET_CALL_REQUEST: 'SET_CALL_REQUEST',
  SET_CURRENT_CALL_REQUEST: 'SET_CURRENT_CALL_REQUEST',
  SET_ACCOUNT_LIST: 'SET_ACCOUNT_LIST',
  SET_STOP_ADDING_REQUEST: 'SET_STOP_ADDING_REQUEST',
  SET_BLOCKCHAIN_LIST: 'SET_BLOCKCHAIN_LIST',
  SET_CAN_SHOW_APP_RATING: 'SET_CAN_SHOW_APP_RATING',
  IS_APP_FIRST_LAUNCH: 'IS_APP_FIRST_LAUNCH',
  SET_GAS_PRICE_SLIDE_VALUE: 'SET_GAS_PRICE_SLIDE_VALUE',
  AI_SEARCH_HISTORY: 'AI_SEARCH_HISTORY',
  SET_ADDRESS_REGISTERED_LIQUIDITY: 'SET_ADDRESS_REGISTERED_LIQUIDITY',
  SET_ADDRESS_DELETED_LIQUIDITY: 'SET_ADDRESS_DELETED_LIQUIDITY',
  ADDRESS_BOOK_HISTORY: 'ADDRESS_BOOK_HISTORY',
  ADDRESS_BOOK_INFO: 'ADDRESS_BOOK_INFO',
  SET_MIGRATION_FLAGS: 'SET_MIGRATION_FLAGS',
  LIST_PRIVATE_KEY_BY_ADDRESS: 'LIST_PRIVATE_KEY_BY_ADDRESS',
  ACTIVE_EVM_CHAIN_IDS: 'ACTIVE_EVM_CHAIN_IDS',
  VAULT_SALT: 'VAULT_SALT',
  VAULT_VERIFY: 'VAULT_VERIFY',
  LOCKOUT_FAILED_ATTEMPTS: 'LOCKOUT_FAILED_ATTEMPTS',
  LOCKOUT_UNTIL: 'LOCKOUT_UNTIL',
  AUTO_LOCK_MINUTES: 'AUTO_LOCK_MINUTES',
  SET_ACCOUNT_TOKEN_LIST: 'SET_ACCOUNT_TOKEN_LIST',
  HISTORY_WC_PAY: 'HISTORY_WC_PAY',
  HISTORY_BACKUP: 'HISTORY_BACKUP',
  LIST_CHAIN_SUPPORT_EXCHANGE: 'LIST_CHAIN_SUPPORT_EXCHANGE',
  // User's device location/region, used to localize content (e.g. where-to-buy
  // links). Shape: { asked: boolean, granted: boolean, country: string } —
  // country '' means declined/unknown.
  SET_USER_LOCATION: 'SET_USER_LOCATION',
  NOTIFICATION_LIST: 'NOTIFICATION_LIST',
  NOTIFICATION_READ_IDS: 'NOTIFICATION_READ_IDS',
  SEND_RECEIVED_HISTORY_BLOCK_TIMESTAMP: 'SEND_RECEIVED_HISTORY_BLOCK_TIMESTAMP'
}

export const REDUX_KEY = {
  accountListRedux: 'accountListRedux',
  activeAccount: 'activeAccount'
}
